export const breedType = [
  "American",
  "Angora (English, French, Giant, Satin)",
  "Belgian Hare",
  "Beveren",
  "Britannia Petite",
  "Californian",
  "Checkered Giant",
  "Chinchilla (American, Giant, Standard)",
  "Cinnamon",
  "Dutch",
  "Dwarf Hotot",
  "English Lop",
  "Flemish Giant",
  "Florida White",
  "French Lop",
  "Harlequin",
  "Havana",
  "Himalayan",
  "Holland Lop",
  "Jersey Wooly",
  "Lionhead",
  "Mini Lop",
  "Mini Rex",
  "Mini Satin",
  "Netherland Dwarf",
  "New Zealand (Red, White, Black)",
  "Palomino",
  "Polish",
  "Rex (Standard, Mini, Castor Rex)",
  "Rhinelander",
  "Satin",
  "Silver Fox",
  "Silver Marten",
  "Tan",
  "Thrianta",
  "Mixed Breed",
  "Unkown",
];

export const rabbitColor = [
  "White",
  "Black",
  "Brown",
  "Gray",
  "Fawn",
  "Agouti",
  "Tan",
  "Blue",
  "Chinchilla",
  "Sooty",
  "Other",
];
